services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: registro_servicos_prestados
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
